function S = SigFit(data)

S = pfit(data,...
    'plot', 'no plot',...
    'matrix_format','xrn','est_gamma',0.5,'verbose','false',...
    'shape','cumulative gaussian','n_intervals',1,...
    'conf',[0.025 0.975],'cuts', 0.5,'sens',8,'runs',1000,... 
    'lambda_equals_gamma',1,'lambda_prior','-flat [0, 0.1]','gamma_prior','-flat [0, 0.1]');
