function [paradigm,subject,timestamp]=dpxdGetFilenameParts(fname)
    if ~ischar(fname)
        error('input must be a string');
    end
    [~,fname]=fileparts(fname); % remove path and extension, does not fail if those are absent
    idx=find(fname=='-');%,2);
    if numel(idx)~=2
        error(['File ''' fname ''' does not contain two hyphens like a regular, autogenerated DPDX filename would.']);
    end
    paradigm=fname(1:idx(1)-1);
    subject=fname(idx(1)+1:idx(2)-1);
    timestamp=fname(idx(2)+1:end);
end
    